#!/bin/sh
set -e

DATE=$(date +%Y%m%d)
rm -f debian/changelog
DISTRO=${DEB_DISTRO:-"$(lsb_release -cs)"}
VERSION=0.1.${DATE}~${DISTRO}
EDITOR=true NAME="Osxie build server" EMAIL=${DEB_EMAIL:-noreply@osxiehq.org} dch -u low -v ${VERSION} --create --distribution ${DISTRO} --package osxie "Daily build"

if [ "$1" = "--dsc" ]; then
    ARG='-S -d'
    if [ -e "../osxie_${VERSION}.orig.tar.xz" ]; then
        rm ../osxie_${VERSION}.orig.tar.xz
    fi
    tar -cJf ../osxie_${VERSION}.orig.tar.xz .
else
    ARG='-b'
fi

debuild --preserve-envvar 'CCACHE_*' --no-lintian -us -uc ${ARG}
