#!/bin/sh
set -e

DATE=$(date +%Y%m%d)
rm -f debian/changelog
DISTRO=${DEB_DISTRO:-"$(lsb_release -cs)"}
VERSION=0.1.${DATE}~${DISTRO}
EDITOR=true NAME="Osxie build server" EMAIL=${DEB_EMAIL:-noreply@osxiehq.org} dch -u low -v ${VERSION} --create --distribution ${DISTRO} --package osxie "Daily build"

ARG='-S'
if [ -e "../osxie_${VERSION}.orig.tar.xz" ]; then
rm ../osxie_${VERSION}.orig.tar.xz
fi
tar -cJf ../osxie_${VERSION}.orig.tar.xz .

debuild --no-lintian -us -uc -S ${ARG}
